
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'eco'
    sourceRepo: 'npm'
    collectBuildInfo: true
    threads: '10'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true

- script: |
    npm run package
  displayName: 'Build the package'

- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'eco'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "*.vsix",
            "target": "npm"
          }
        ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    failNoOp: true


- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'eco'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'


- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'eco'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: true

- task: ArtifactoryBuildPromotion@1
  inputs:
    artifactoryService: 'eco'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    targetRepo: 'staging-local'
    status: 'Released'
    includeDependencies: false
    copy: false
    dryRun: false
